// Generated by gencpp from file encoder/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ENCODER_MESSAGE_ADDTWOINTS_H
#define ENCODER_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <encoder/AddTwoIntsRequest.h>
#include <encoder/AddTwoIntsResponse.h>


namespace encoder
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace encoder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::encoder::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::encoder::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::encoder::AddTwoInts > {
  static const char* value()
  {
    return "encoder/AddTwoInts";
  }

  static const char* value(const ::encoder::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::encoder::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::encoder::AddTwoInts > 
template<>
struct MD5Sum< ::encoder::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::encoder::AddTwoInts >::value();
  }
  static const char* value(const ::encoder::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::encoder::AddTwoIntsRequest> should match 
// service_traits::DataType< ::encoder::AddTwoInts > 
template<>
struct DataType< ::encoder::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::encoder::AddTwoInts >::value();
  }
  static const char* value(const ::encoder::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::encoder::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::encoder::AddTwoInts > 
template<>
struct MD5Sum< ::encoder::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::encoder::AddTwoInts >::value();
  }
  static const char* value(const ::encoder::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::encoder::AddTwoIntsResponse> should match 
// service_traits::DataType< ::encoder::AddTwoInts > 
template<>
struct DataType< ::encoder::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::encoder::AddTwoInts >::value();
  }
  static const char* value(const ::encoder::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ENCODER_MESSAGE_ADDTWOINTS_H
